config/routes.rb
Rails.application.routes.draw do
  scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do
    resources :users
    resources :posts do
      resources :comments
    end
    resources :sessions, only: [:new, :create, :destroy]
    get "signup", to: "users#new", as: "signup"
    get "login", to: "sessions#new", as: "login"
    post "login", to: "sessions#create"
    get "logout", to: "sessions#destroy", as: "logout"
    root 'posts#index'
    delete '/post/:id', to: "posts#destroy", as: 'delete_post'
  end
  post "login", to: "sessions#create"
  get '', to: redirect("/#{I18n.default_locale}")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy 
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true
  has_many :posts, dependent: :destroy 
  has_many :comments, dependent: :destroy 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery
    before_action :set_locale   
    def set_locale
        I18n.locale = params[:locale] if params[:locale].present?
    end
        
    def default_url_options(options = {})
        options.merge(locale: I18n.locale)
    end
    helper_method :current_user

    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        else
            @current_user = nil
        end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        if current_user
            @post = Post.find(params[:post_id])
            @comment = @post.comments.create(user_id: session[:user_id], content: comment_params[:content])
            redirect_to post_path(@post)
        else
            redirect_to :login, notice: "You need to log in to access more pages"
        end
    end
  
    def destroy
        if current_user
            @post = Post.find(params[:post_id])
            @comment = @post.comments.find(params[:id])
            @comment.destroy
            redirect_to post_path(@post)
        else
            redirect_to :login, notice: "You need to log in to access more pages"
          end
    end  

    private
    def comment_params
        params.required(:comment).permit(:content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all.order("created_at DESC")
    end
  
    def new
        if current_user
            @post = Post.new
        else
            redirect_to :login, notice: "You need to log in to access more pages"
          end
    end
  
    def create
        if current_user
            @post = Post.new(user_id: session[:user_id], title: post_params[:title], content: post_params[:content], topic: post_params[:topic])
            if @post.save
                redirect_to posts_path
            else
                render 'new'
            end
        else
            redirect_to :login, notice: "You need to log in to access more pages"
          end
    end
  
    def show
        if current_user
            @post = Post.find(params[:id])
        else
            redirect_to :login, notice: "You need to log in to access more pages"
        end
    end
  
    def update
        if current_user
            @post = Post.find(params[:id])
    
            if @post.update(post_params)
                redirect_to @post
            else
                render 'edit'
            end
        else
            redirect_to :login, notice: "You need to log in to access more pages"
          end
    end
  
    def edit
        if current_user
            @post = Post.find(params[:id])
        else
            redirect_to :login, notice: "You need to log in to access more pages"
        end
    end
  
    def destroy
        if current_user
            @post = Post.find(params[:id])
            @post.destroy
            puts "DESTROYED"
            redirect_to posts_path 
        else
            redirect_to :login, notice: "You need to log in to access more pages"
          end 
    end
  
    private
  
    def post_params
        params.require(:post).permit(:title, :content, :topic)
    end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session[:user_id] = nil;
  end
  
  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      session[:user_name] = user.username
      redirect_to :root, notice: 'User logged in'        
    else
      redirect_to login_path, notice: 'Invalid Email or Password'
    end
  end
    
  def destroy
    session[:users_id] = nil
    redirect_to :login, notice: 'User logged out'   
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if current_user
      @users = User.all
    else
      redirect_to :login, notice: "You need to log in to access more pages"
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to :root #sau sua thanh root
    else
      redirect_to :new_user, notice: "Invalid information. Cannot register"
    end
  end
  
  def show
    if current_user
      @user = User.find(params[:id])
    else
      redirect_to :login, notice: "You need to log in to access more pages"
    end
  end

  def update
    if current_user
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to :root #sau sua thanh root
      else
        redirect_to :edit, notice: "Invalid information. Cannot save changes"
      end
    else
      redirect_to :login, notice: "You need to log in to access more pages"
    end
  end
  
  def edit
    if current_user
      @user = User.find(params[:id])
    else
      redirect_to :login, notice: "You need to log in to access more pages"
    end
  end
  
  def destroy
    if current_user
      @user = User.find(params[:id])
      @user.destroy  
      redirect_to :root #sau se sua
    else
      redirect_to :login, notice: "You need to log in to access more pages"
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <div>
            <%=image_tag "user.png", class:"avatar-cmt avatar for-user"%> 
            <strong><%= comment.user.username %></strong> 
          </div>
          <div class="cmt-content"><%= comment.content %></div>
        </p>
      </div>
    </div>
    <div class="side-btn" style="margin-right:10px">
      <%= link_to t('.delete'), [comment.post, comment],
                  method: :delete, class: "side-btn-link", data: { confirm: 'Are you sure?' } %>
    </div>
  </article>
</div>

app/views/comments/_new.html.erb
<div class="section">
<%= form_for [@post, Comment.new]  do |form| %>
    <table>
    <td style="vertical-align:middle">
    <div class="field cmt-items">
      <div class="control">
        <%=image_tag "user.png", class:"avatar-cmt avatar for-user"%> 
        <%= form.text_area :content%>
      </div>
    </div>
    </td>
    <td>
    <div class="actions cmt-items">
        <%= form.submit t('.send'), class: "btn btn-form" %>
    </div>
    </td>
    </table>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Commu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!--Navbar-->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-md">
        <%= link_to 'Commu', root_path, class: "navbar-brand"  %>
    </div>
    <div class="nav navbar-right">
      <ul class="nav navbar-nav navbar-right">
        <%if !current_user %>
          <li><button type="button" class="btn"><%= link_to t('.log-in'), login_path %></button></li>
          <li><button type="button" class="btn"><%= link_to t('.sign-up'), new_user_path %></button></li>
        <%else%>
          <li><button type="button" class="btn"><%= link_to t('.create-post'), new_post_path %></button></li>
          <li><button type="button" class="btn"><%= link_to t('.profile'), user_path(current_user) %></button></li>
          <li><button type="button" class="btn"><%= link_to t('.log-out'), logout_path %></button></li>          
        <%end%>
        <li><%= link_to 'English', locale: "en" %></li> |
        <li><%= link_to 'Русский', locale: "ru" %></li>
      </ul>
    </div>
  </nav>
  <!--End of Navbar-->     
  <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="show-post-card">
  <div class="section">
  <%= form_with(model: @post) do |form| %>
      <fieldset>
        <legend>Edit post</legend>
          <div class="mb-3 row">
            <%= form.label :title, class: "col-sm-2 col-form-label" %>  
            <div class="col-sm-8">
              <%= form.text_field :title, class: "form-control" %>
            </div>          
          </div>      
          <div class="mb-3 row">
            <%= form.label :content, class: "col-sm-2 col-form-label" %>  
            <div class="col-sm-8">
              <%= form.text_area :content, rows: 17,  class: "form-control text-area-post" %>
            </div>          
          </div>    
          <div class="mb-3 row">
            <div class="col-sm-2 col-form-label"><strong>Topic</strong></div>
            <div class="col-sm-8">
              <%= form.radio_button :topic, 'travel' %>
              <%= form.label :topic, 'Travel', :value => 'travel' %>
              <%= form.radio_button :topic, 'food' %>
              <%= form.label :topic, 'Food', :value => 'food' %>
              <%= form.radio_button :topic, 'pet' %>
              <%= form.label :topic, 'Pet', :value => 'pet' %>   
              <%= form.radio_button :topic, 'work' %>
              <%= form.label :topic, 'Work', :value => 'work' %>   
              <%= form.radio_button :topic, 'flower' %>
              <%= form.label :topic, 'Flower', :value => 'flower' %>  
              <%= form.radio_button :topic, 'friend' %>
              <%= form.label :topic, 'Friend', :value => 'friend' %>  
              <%= form.radio_button :topic, 'love' %>
              <%= form.label :topic, 'Love', :value => 'love' %> 
            </div>   
          </div> 
          <div class="actions group-btn">
            <%= form.submit "Update post", class: "btn btn-form" %>
          </div>                          
      </fieldset>
  <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<% content_for :page_title,  "Index" %>

<div class="section">
  <div class="container">
    <% @posts.each do |post| %>
      <div class="card-post">
        <table>
          <tr>
            <td colspan="1" class="thumb">
              <div>       
                <%=image_tag "#{post.topic}.jpg", class: "thumbnail"%>       
              </div>
            </td>
            <td colspan="5">
              <div class="post-content">
                <div> 
                  <%=image_tag "user.png", class:"avatar for-user"%>
                  <p class="post-user for-user"><%= "- #{post.user.username}"%> </p>
                </div>
                
                <p class="post-title"><%= "#{post.title}"%></p>                
              </div>              
            </td>
            <td>
              <div class="side-btn">
                <div class="side-btn">
                  <%= link_to t('.read'), post_path(locale, post), class: "side-btn-link" %> |
                  <%= link_to t('.edit'), edit_post_path(locale, post), class: "side-btn-link" %> |
                  <%= link_to t('.delete'), post, method: :delete, class: "side-btn-link", data: { confirm: 'Are you sure?' } %>
                </div>
              </div>
            </td>
          <tr>
        </table>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<!--new-->
<div class="show-post-card">
  <div class="section">
  <%= form_with(model: @post) do |form| %>
      <fieldset>
        <legend>Create new post</legend>
          <div class="mb-3 row">
            <%= form.label :title, class: "col-sm-2 col-form-label" %>  
            <div class="col-sm-8">
              <%= form.text_field :title, class: "form-control" %>
            </div>          
          </div>      
          <div class="mb-3 row">
            <%= form.label :content, class: "col-sm-2 col-form-label" %>  
            <div class="col-sm-8">
              <%= form.text_area :content, rows: 17,  class: "form-control text-area-post" %>
            </div>          
          </div>    
          <div class="mb-3 row">
            <div class="col-sm-2 col-form-label"><strong>Topic</strong></div>
            <div class="col-sm-8">
              <%= form.radio_button :topic, 'travel' %>
              <%= form.label :topic, 'Travel', :value => 'travel' %>
              <%= form.radio_button :topic, 'food' %>
              <%= form.label :topic, 'Food', :value => 'food' %>
              <%= form.radio_button :topic, 'pet' %>
              <%= form.label :topic, 'Pet', :value => 'pet' %>   
              <%= form.radio_button :topic, 'work' %>
              <%= form.label :topic, 'Work', :value => 'work' %>   
              <%= form.radio_button :topic, 'flower' %>
              <%= form.label :topic, 'Flower', :value => 'flower' %>  
              <%= form.radio_button :topic, 'friend' %>
              <%= form.label :topic, 'Friend', :value => 'friend' %>  
              <%= form.radio_button :topic, 'love' %>
              <%= form.label :topic, 'Love', :value => 'love' %>  
            </div>   
          </div> 
          <div class="actions group-btn">
            <%= form.submit "Post", class: "btn btn-form" %>
          </div>                          
      </fieldset>
  <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="show-post-card">
  <h2><%= @post.title %></h2>
  <%=image_tag "user.png", class:"avatar for-user"%>
  <h5 class="for-user"><%= " - #{@post.user.username}"%></h5>  
  <div class="side-btn">
    <%= link_to t('.edit'), edit_post_path(@post), class: "side-btn-link" %> |
    <%= link_to t('.back'), root_path, class: "side-btn-link"%> 
  </div>
  <hr class="solid">
  <p><%= @post.content %></p>
</div>

<div class="show-post-card">
  <section class="section comments">
    <div class="container">
        <h2 class="count-cmt"><%= @post.comments.count %> <%=t('.comments') %></h2>
        <%= render @post.comments%>
        <div class="comment-form">
            <hr />
            <h3 class="cmt-label"><%=t('.write-your-cmt')%></h3>
             <%= render 'comments/new' %>
        </div>
    </div>
  </section>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user) do |form| %>
    <div class="field">
      <div class="control">
        <%= form.label :username %>
        <%= form.text_field :username %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= form.label :email %>
        <%= form.text_field :email %>
      </div>  
    </div>

    <div class="field">
      <div class="control">
        <%= form.label :password %>
        <%= form.password_field :password %>
      </div>  
    </div>

    <div class="field">
      <div class="control"> 
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation %>
      </div>  
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
    <% end %>

app/views/users/edit.html.erb
<h1>EDIT PROFILE</h1>

<div class="section">    
  <%= render 'form', user: @user %>
</div>

<%= link_to 'Back', users_path %> |

app/views/users/index.html.erb
<h1>USERS/INDEX_TABLE INFORMATION OF ALL USERS</h1>
<table class="table table-bordered">
        <tr>
            <th>ID</th>
            <th>Username</th>
            <th>Email</th>
            <th>Created at</th>
            <th>Updated at</th>
            <th></th>
            <th></th>
        </tr>
        <% @users.each do |user|%>
        <tr>
            <td><%= user.id %></td>
            <td><%= user.username %></td>
            <td><%= user.email %></td>
            <td><%= user.created_at %></td>
            <td><%= user.updated_at %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
        </tr>
        <% end %>
</table>

app/views/users/new.html.erb
  <div id="login-card" class="container align-self-center">
                <%= form_with(model: @user) do |form| %>
                    <fieldset>
                        <legend>Sign up</legend>
                        <p id="notice"><%= notice %></p>
                        <div class="field">
                         <div class="mb-3 row">
                            <%= form.label :username, class: "col-sm-2 col-form-label" %>
                            <div class="col-sm-8">
                                <%= form.text_field :username, class: "form-control" %>
                            </div>          
                        </div>     
                        <div class="mb-3 row">
                            <%= form.label :email, class: "col-sm-2 col-form-label" %>
                            <div class="col-sm-8">
                                <%= form.text_field :email, class: "form-control" %>
                            </div>          
                        </div>      
                         <div class="mb-3 row">
                            <%= form.label :password, class: "col-sm-2 col-form-label" %>
                            <div class="col-sm-8">
                                <%= form.password_field :password, class: "form-control" %>
                            </div>          
                        </div>    
                         <div class="mb-3 row">
                            <%= form.label :password_confirmation, class: "col-sm-2 col-form-label" %>
                            <div class="col-sm-8">
                                <%= form.password_field :password_confirmation, class: "form-control" %>
                            </div>          
                        </div>    
                        <div class="group-btn actions">            
                            <%= submit_tag "Sign up", class: "btn btn-form" %>
                            <button type="button" class="btn btn-form"><%= link_to 'Login', login_path %></button>
                        </div>           
                    </fieldset>
                <% end %>
    </div>

app/views/users/show.html.erb
<h1>PROFILE</h1>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |